### PR TITLE
docs(README.md): fixes spelling and grammar

### PR DESCRIPTION
**Pull request by melindabernrdo**

### CODE REVIEW

**Comment by tomchentw** [comment]
Thanks a lot! Would you mind to change your commit message to this:
```
docs(README.md): fixes spelling and grammar
```

**Comment by melindabernrdo** [comment]
No problem! Happy to help.

**Comment by tomchentw** [comment]
Oops, I mean the git commit message. You could change it with the following commit:
```
git commit --amend
```
After that, you'll need to do:

```
git push --force
```

**Comment by tomchentw** [comment]
Since I've just merged #179, could you please did a rebase to the latest upstream?
```
git add remote upstream https://github.com/tomchentw/react-google-maps.git
git fetch upstream
git rebase -i upstream/master
```
After that, you could change it with the following command:
```
git commit --amend
```
After that, you'll need to do:

```
git push --force
```

**Pull request closed without merging**
