### PR TITLE
Set explicit dependency versions

### PR DESCRIPTION
**Pull request by oshalygin**
- This change is to ensure that packages are not moving
  the ground underneath the project and introducing
  breaking changes.
- As the project progresses, these packages will be updated
  accordingly and to the latest version if there are improvements
  in the dependency.
- Peer dependencies will be updated on a very regular basis.
- create-react-class was updated to 15.5.3 due to a known
  issue with browserify

### CODE REVIEW

**Comment by tomchentw** [comment]
@oshalygin be sure to follow commit message formats for the future PRs (for auto-generated CHANGELOG.md)

**Comment by oshalygin** [comment]
@tomchentw will do!

**Comment by tomchentw** [comment]
Released [v7.3.0](https://github.com/tomchentw/react-google-maps/releases/tag/v7.3.0)

**Comment by tomchentw** [comment]
@oshalygin I think it should be fine leaving `devDependencies` open, as our dependencies are locked by `yarn.lock`. I'm OK with exact `dependencies & peerDependencies`, although personally I don't use this pattern in other projects.

**Comment by oshalygin** [comment]
Good call thanks @tomchentw !

**Pull request merged**
