### PR TITLE
Permit React 15 to be included as a peer dependency.

### PR DESCRIPTION
**Pull request by evcohen**

### CODE REVIEW

**Comment by dptoot** [comment]
+1 Stable 15 build was released yesterday. Can we update peer dependencies?

**Comment by agroves333** [comment]
+1

**Comment by vvo** [comment]
cc @tomchentw :)

**Comment by EvNaverniouk** [comment]
Unfortunately this PR isn't enough because `react-google-maps` depends on `react-prop-types-element-of-type` which also doesn't support React 15.

**Comment by neoziro** [comment]
+1

**Comment by kgcmd** [comment]
+1

**Comment by tomchentw** [comment]
Published [v4.10.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.10.0)

**Comment by EvNaverniouk** [comment]
Thanks @tomchentw . Could you also update the `dependency` of `react-prop-types-element-of-type` to version `2.1.0` as well? Otherwise we still get `npm` complaining about unmet dependencies.

**Comment by tomchentw** [comment]
@EvNaverniouk My bad. Will fix it.

**Comment by tomchentw** [comment]
Published [v4.10.1](https://github.com/tomchentw/react-google-maps/releases/tag/v4.10.1)

**Pull request merged**
