### PR TITLE
added more supported map options

### PR DESCRIPTION
**Pull request by bruno12mota**
Hey! There are more supported options which were being ignored in the composeOptions function. Added a few more that I used in my case.

Cheers!

### CODE REVIEW

**Comment by tomchentw** [comment]
Same reason for #112 here. For `google.maps.Map` only these props are controlled/uncontrolled and it's determined by the following lines:

https://github.com/tomchentw/react-google-maps/blob/081d03f10a7200952c65f7994e896fb3d96d3bc5/src/creators/GoogleMapHolder.js#L14-L16

You should just use `<GoogleMap options={{}} ....>` or  `<GoogleMap defaultOptions={{}} ....>` instead.

**Comment by bruno12mota** [comment]
Oh, sorry. Makes sense, didn't see it on the documentation though, my bad.

Great work by the way :+1:

**Comment by tomchentw** [comment]
Really sorry about that. Haven't find a good documentation tool yet. Any recommendations?

**Comment by bruno12mota** [comment]
Well there isn't something that stands out for documentation out there for free at least. I'm building my project docs with [Jekyll](https://jekyllrb.com/) so that people can contribute later. This is how react does it as well https://github.com/facebook/react/tree/gh-pages

The pain is more in setting up the design for it, I'll be making a custom one for my project, it's all open source so you can use it for this repo of course :-)

**Pull request closed without merging**
