### PR TITLE
fix(GoogleMaps): VirtualContainer renders as child of GoogleMaps

### LINKED ISSUE #47: Wrapper component lifecycle issue
The `GoogleMaps` wrapper component breaks the React lifecycle because it does not re-render the VirtualContainer until [after it is done updating everything](https://github.com/tomchentw/react-google-maps/blob/master/src/GoogleMaps.js#L79).

This means trying to get an updated value from a newly-changed `Marker`, for example, is not possible in any parent component's `componentDidUpdate` method, because the children of the VirtualContainer are not yet re-rendered.

This is a regression from the previous mixin/context methodology, and leads to very confusing and difficult to debug errors.

Perhaps one solution would be to re-render VirtualContainer on `componentWillUpdate` instead.

### PR DESCRIPTION
**Pull request by idolize**
This allows DOM elements to render inside <GoogleMaps> as well as Google Map elements. This also fixes #47.

### CODE REVIEW

**Comment by idolize** [comment]
@tomchentw

**Comment by tomchentw** [comment]
Interesting. Will `<VirtualContainer>` inside the div get clear when React diff algorithm take place? Since `window.google.maps.Map` will also render DOM into the div.

**Comment by idolize** [comment]
@tomchentw Good question. What's the best way to test that? Are you saying that the `VirtualContainer` *should* or *should not* be cleared each time the diff happens?

I've been using this branch myself for a while now, and I haven't seen any warnings from React about the DOM being mutated unexpectedly.

**Comment by tomchentw** [comment]
@idolize just dynamically add more contents to the children of `<GoogleMaps>`. For examples, change `<Marker>` counts from one to three.

**Comment by idolize** [comment]
I just tried this (using [the `event-arguments` example code](https://tomchentw.github.io/react-google-maps/#events/event-arguments)) and it works as expected—the `<Marker>`s are not cleared.

**Comment by idolize** [comment]
@tomchentw Any chance of getting this merged? Thanks!

**Comment by tomchentw** [comment]
Released as [v1.5.0](https://github.com/tomchentw/react-google-maps/releases/tag/v1.5.0)

**Pull request closed without merging**
