### PR TITLE
Let `OverlayView` be clusterd in `MarkerClusterer`

### PR DESCRIPTION
**Pull request by ziad-saab**
Since `OverlayView` can represent any kind of overlay, including extremely
custom markers, it makes sense to allow it to be clustered. For this to work,
we only have to implement two functions of the `Marker` class: `getDraggable`
and `getPosition`.

The `MarkerClusterer` will call our `OverlayView`'s `setVisible` method as
needed.

### CODE REVIEW

**Comment by riaan53** [comment]
This will be great!

**Comment by cristiandley** [comment]
@ziad-saab if you want see this in a repo check https://github.com/cristiandley/react-gl-maps we are trying to promote all this PR that are helpful

**Comment by tomchentw** [comment]
We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Comment by tomchentw** [comment]
Released [v4.11.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.11.0).

We're also looking for maintainers. Involve in #266 to help strengthen our community!

**Pull request merged**
