### PR TITLE
Add bounds to overlay view

### PR DESCRIPTION
**Pull request by uriklar**

### CODE REVIEW

**Comment by ilyagelman** [comment]
@tomchentw This is a very useful one, could you please consider merging?

**Comment by tomchentw** [comment]
Thanks! Released [v4.9.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.9.0)

**Comment by tomchentw** [comment]
Feel free to open up a PR to add an example to `example/gh-pages`!

**Comment by uriklar** [comment]
Hi @tomchentw . Thanks for merging! I actually did add an example to gh-pages. It's in:
examples/gh-pages/scripts/components/basics/OverlayView.js

**Comment by tomchentw** [comment]
@uriklar yeah, but I thought you just added a comment?

**Comment by tomchentw** [comment]
I found that changing from `cDU` to `cWRP` will fail the test case. I just reverted and released a new version [v4.9.1](https://github.com/tomchentw/react-google-maps/releases/tag/v4.9.1).

Please raise up a PR of this issue if you think it's a better way to go and have fixed the failing test cases, thanks!

**Pull request closed without merging**
