### PR TITLE
MarkerWithLabel utility support for custom pins

### PR DESCRIPTION
**Pull request by RGFnaGFuIEd1bmF5**
#565

### CODE REVIEW

**Comment by RGFnaGFuIEd1bmF5** [comment]
When i was trying to change the label content, it wasn't re-render the overlay.Then, I have added getter and setter for it.

There is more question here now.Should i support it with jsx? In my project, I have just handled with the template string but it start to seems confusing.

**Comment by oshalygin** [comment]
Thanks @RGFnaGFuIEd1bmF5 I'll leave this open for now and test it early this week.  If someone else gets to it before me we'll merge it as well.

**Comment by RGFnaGFuIEd1bmF5** [comment]
Nice! After test i will squash my commits.

**Comment by wuzyk** [comment]
Any news on this PR?

**Comment by oshalygin** [comment]
Merged, this worked fairly well.  I'm still a bit on the fence of adding custom styles to this repo for demonstration purposes as we talked about in the last PR.  That said, I don't want to hold up this feature, this was good stuff much appreciated!!

**Comment by tomchentw** [comment]
One thing for @oshalygin , `feat(marker):` should be `feat(Marker):`. Otherwise, great job!!!!!!!!!!!!!!!

**Comment by tomchentw** [comment]
Released [v7.3.0](https://github.com/tomchentw/react-google-maps/releases/tag/v7.3.0)

**Pull request merged**
