### PR TITLE
Marker animation fix

### PR DESCRIPTION
**Pull request by danielroth**
Currently a markers animation runs on every state change, this patch makes sure to only set the animation on the initial run.

### CODE REVIEW

**Comment by danielroth** [comment]
A better way to implement this could be to diff the props and only apply the props that has changed. What are your thoughts @tomchentw?

**Comment by tomchentw** [comment]
@danielroth I agree. We have some discussion in #44. How would you implement it?
For the PR, please fix the commit messages to:
```
fix(SimpleChildComponent): make sure to only animate markers on the first run
chore(examples): edit the GettingStarted example to demonstrate that animations
```

**Comment by danielroth** [comment]
@tomchentw I updated the commit messages as you requested.

**Comment by tomchentw** [comment]
Great!

**Comment by tomchentw** [comment]
Published as [v1.4.0](https://github.com/tomchentw/react-google-maps/releases/tag/v1.4.0)

**Pull request merged**
