### PR TITLE
feat(async/ScriptjsLoader): rename from async/ScriptjsGoogleMap

### PR DESCRIPTION
**Pull request by tomchentw**
This is a rewrite based on issue of #145 . Could @mattjstar please help review this? Thanks!

### CODE REVIEW

**Comment by tomchentw** [comment]
Released [v4.5.0](https://github.com/tomchentw/react-google-maps/releases/tag/v4.5.0)

**Comment by mattjstar** [comment]
Awesome, looks great thanks so much @tomchentw !

**Comment by tomchentw** [comment]
Thanks for the inspiration from @mattjstar. I also update the synchronous version to a loader approach in #157. Make sure to check it out for latest update of async API as well.

**Comment by mattjstar** [comment]
perfect, thanks for handling the change so quick!

**Pull request merged**
