### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by romseguy**
Import completeness

### CODE REVIEW

**Comment by oshalygin** [comment]
Guys we need to merge this sort of stuff.  It's from Feb 14!

**Comment by thomasbeta** [comment]
The same change is needed on line 187.

**Comment by oshalygin** [comment]
@tomchentw please delegate access :)

**Comment by tomchentw** [comment]
Dup of merged #438.

**Comment by tomchentw** [comment]
Released [v6.0.2](https://github.com/tomchentw/react-google-maps/releases/tag/v6.0.2)

**Pull request closed without merging**
