### PR TITLE
Add comments to add reference to GoogleMaps API to have google.maps reference

### PR DESCRIPTION
**Pull request by taydakov**
I spent some time to figure it out by myself. So that would be a very helpful comment for me.

### CODE REVIEW

**Comment by ksavenkov** [comment]
Just killed a couple of hours on that, thanks :-)

**Comment by tomchentw** [comment]
Thanks for the link.

**Comment by tomchentw** [comment]
TODO: add this in #88

**Comment by tomchentw** [comment]
Released [v2.0.0] and [v2.0.1].

[v2.0.0]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.0
[v2.0.1]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.1

**Pull request closed without merging**
