### PR TITLE
[Marker] Prevent Marker from redrawing MarkerClusterer when being added / removed

### PR DESCRIPTION
**Pull request by amangeot**
Hello,
I'm trying to solve this issue: https://github.com/tomchentw/react-google-maps/issues/395

The idea is to prevent Marker from redrawing MarkerClusterer when being added / removed using `markerclustererplus` noredraw option.

The current implementation adds `noRedraw` to `Marker` props, but I believe it bypasses a potential `defaultNoRedraw`.

### CODE REVIEW

**Comment by toddw** [comment]
Would it be possible to modify this so it works for polygons as well?

**Comment by amangeot** [comment]
I don't know about Polygons and MarkerClusterer but @mikkelwf made it happen with OverlayView in https://github.com/tomchentw/react-google-maps/pull/358

**Comment by toddw** [comment]
So my issue with polygons was actually caused because I was creating a component using `withScriptJs(withGoogleMap(…))` inside of the render method. Moved it outside of the render method and my problem with polygons went away.

**Comment by gergely-ujvari** [comment]
Any chance that this might that reviewed and merged?

**Comment by tymarats** [comment]
The second commit looks reasonable to me (if the prop is not used, it works the same as by default). Tom, are there any obstacles for merging this?

**Comment by tomchentw** [comment]
Released [6.3.0](https://github.com/tomchentw/react-google-maps/releases/tag/v6.3.0)

**Pull request closed without merging**
