### PR TITLE
KmlLayer support

### PR DESCRIPTION
**Pull request by ydogandjiev**
This change adds support for KmlLayers to react-google-maps. It also adds a KmlLayer example to gh-pages based on Google's own tutorial found here:
https://developers.google.com/maps/documentation/javascript/examples/layer-kml

Please let me know if I've missed anything and I will take care of it ASAP.

### CODE REVIEW

**Comment by tomchentw** [comment]
@ydogandjiev looks good. Few things about commit message:
1. Please don't compile `lib` in the commits. We'll do this with release scripts
2. Please change the first commit message to: `feat(KmlLayer): add new KmlLayer component`
3. Please change the second commit message to: `docs(gh-pages): add KmlLayer example`

**Comment by ydogandjiev** [comment]
@tomchentw thanks for the feedback. I will open a new pull request with the updated changes.

**Comment by tomchentw** [comment]
Thanks! New PR merged in #194 .

**Comment by sco-tt** [comment]
@ydogandjiev how would I set `preserveViewport` to `true` as outlined in https://developers.google.com/maps/documentation/javascript/3.exp/reference#KmlLayer

**Comment by tomchentw** [comment]
@sco-tt : `<KmlLayer options={{preserveViewport: true}} />`

**Comment by sco-tt** [comment]
@tomchentw Thanks!

**Pull request closed without merging**
