### PR TITLE
Add Rectangle shape

### PR DESCRIPTION
**Pull request by alistairjcbrown**
Adds in a new `Rectangle` shape with [available `bounds_changed`](https://developers.google.com/maps/documentation/javascript/shapes#editable_events) event.

This should fix issue https://github.com/tomchentw/react-google-maps/issues/79

```jsx
import { Rectangle } from 'react-google-maps';

let bounds = new google.maps.LatLngBounds(
  new google.maps.LatLng(-34.04355650412745, 150.99609375),
  new google.maps.LatLng(-33.68321092658006, 151.4300537109375)
);

<Rectangle
  ref="shape"
  clickable={true}
  draggable={true}
  editable={true}
  onBoundsChanged={() => {
    console.log('Bounds changed');
  }}
  bounds={bounds} />
```

### CODE REVIEW

**Comment by alistairjcbrown** [comment]
Hi @tomchentw - give me a shout if there's anything else needed for this PR.
it should be a fairly minimal change (most of the diff is the built files) and just adds the Rectangle shape in the same was as the Circle.

**Comment by alistairjcbrown** [comment]
Hi @tomchentw - just thought I'd give this a bump - is this good to be merged?

**Comment by tomchentw** [comment]
TODO: add this in #88

**Comment by tomchentw** [comment]
Hi @alistairjcbrown , sorry for the late response. 
I took a day to rewrite the module from scratch on #88 . It will be great if you could take a look at it. Thanks!

**Comment by tomchentw** [comment]
Released [v2.0.0] and [v2.0.1].

[v2.0.0]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.0
[v2.0.1]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.1

**Pull request closed without merging**
