### PR TITLE
Feature/map on load

### PR DESCRIPTION
**Pull request by mbahoshy**
onLoad prop for map component. useful for setting event listeners on map object

### CODE REVIEW

**Comment by tomchentw** [comment]
Sorry, I'm doing a refactoring at the moment. Would you consider raise this again afterwards? Some review comments:

1. don't compile `lib`, I'll do it for you
2. what kind of event listeners do you need that is not supported by `react-google-maps` currently?

**Comment by tomchentw** [comment]
#157 is landed. Would you consider revisit this again?

Actually I'm not a big fan of exposing `google map` object to the outside. It may lead to misuse of the object and lose the advantage of using React.

**Comment by mbahoshy** [comment]
@tomchentw I was trying to set an event listener for "center_changed" on the map object. Is there currently a way to do this? The callback is nice because it lets you add any logic that may need to take place once the map has been created.

**Comment by tomchentw** [comment]
@mbahoshy the `center_changed` is supported and you can set it via `props.onCenterChanged` on the `<GoogleMap>` component. 
https://github.com/tomchentw/react-google-maps/blob/master/src/eventLists/GoogleMapEventList.js#L5

See `Geojson` example for using `onZoomChanged`:
https://tomchentw.github.io/react-google-maps/#geojson

**Comment by mbahoshy** [comment]
@tomchentw thanks exactly what I am looking for, I missed this feature. I could still see the virtue of an onLoad function, maybe w/o map object in callback.

**Comment by tomchentw** [comment]
You don't need `onLoad` after #157 is landed with `callback` refs. At the time the callback is invoked, the component is initialized and loaded.

**Pull request closed without merging**
