### PR TITLE
Bicycling Layer

### PR DESCRIPTION
**Pull request by david-mart**
Simple [BicyclingLayer class](https://developers.google.com/maps/documentation/javascript/3.exp/reference#BicyclingLayer) implementation, based on current _TrafficLayer_ component

### CODE REVIEW

**Comment by oshalygin** [comment]
Thanks for this! Please resolve the conflicts and we can review 🗡

**Comment by david-mart** [comment]
@tomchentw Thanks!

**Comment by david-mart** [comment]
Removed the file as requested

**Comment by tomchentw** [comment]
Released [v8.4.0](https://github.com/tomchentw/react-google-maps/releases/tag/v8.4.0)

**Pull request merged**
