### PR TITLE
Fixed react  lifecycle methods warning

### PR DESCRIPTION
**Pull request by puviz**
fix: adding “UNSAFE_” prefix to react  lifecycle methods.

### CODE REVIEW

**Comment by JustFly1984** [comment]
@puviz this library is unmaintained almost 2 years, please refer to new lib npm @react-google-maps/api

**Comment by puviz** [comment]
> @puviz this library is unmaintained almost 2 years, please refer to new lib npm @react-google-maps/api

@JustFly1984 thank you for your suggestion

**Comment by barrard** [comment]
I ran the command
```bash
npx react-codemod rename-unsafe-lifecycles

```
 to fix this issure, but im still getting the warnings.  How did you accomplish this? thanks.

**Comment by JustFly1984** [comment]
@barrard this library is unmaintained more than two years and will never be updated. Please refer to our rewrote and updated version: @react-google-maps/api

**Comment by barrard** [comment]
@JustFly1984  Thanks for your work on this new library.  It seems to be missing `MarkerWithLabel` which I want to use.

**Comment by JustFly1984** [comment]
@barrard If you need it, your PR is welcome, you can create a new package in our repo, and I will publish it and update the main library, just copy marker-clusterer, and replace the code inside the copy

**Pull request closed without merging**
