### PR TITLE
Support for drawing API

### LINKED ISSUE #28: Drawing API support
@tomchentw 
Is there any support for the [Google Maps drawing API](https://developers.google.com/maps/documentation/javascript/drawinglayer) via this project?

This is **crucial** for me, so if it's not built in, is there a way I can get a reference to the underlying Google Maps `map` object so I can point a `DrawingManager` I instantiate at it?

### PR DESCRIPTION
**Pull request by idolizesc**
Resolves #28 and exposes `DrawingManager` as `require("react-google-maps").drawing.DrawingManager`

### CODE REVIEW

**Comment by tomchentw** [comment]
Thanks for @idolizesc contribution! However, I just revamp the api and merged in #32. Would you like to revamp on this, too?

**Comment by idolizesc** [comment]
@tomchentw Yes, absolutely. Once I get a chance I will work on updating my change. Thanks!

**Comment by idolize** [comment]
Submitted new PR as #46 (and under my personal GitHub account rather than my work one :P)

**Comment by tomchentw** [comment]
Close this for #46. Great work thanks @idolize and @idolizesc LOL

**Pull request closed without merging**
