### PR TITLE
feat(StreetViewPanorama): add StreetViewPanorama component

### PR DESCRIPTION
**Pull request by novascreen**
I was using react-google-maps for my projects for regular map stuff and StreetView, so it seemed most convenient to follow the implementation of the other Google Maps features to add StreetView. Super clean mapping between React and the options, events and everything 👍 
Would be great if this could be included in this library.

### CODE REVIEW

**Comment by tomchentw** [comment]
Thanks for the contribution! Most parts look good.

I'm not sure if I like the approach of using `props.element` to render `StreetViewPanorama` component independently. This API interface doesn't conform our interfaces in general. (But I don't have any other thoughts)

**Comment by novascreen** [comment]
hey @tomchentw 
i had to do a fix for the standalone part and the deprecation warnings. I've renamed the prop to `containerElement` to at least align that with the prop for `withGoogleMap`.
I realize this doesn't align with the other components, but it's a special case in the Google Maps API for StreetView that allows you to do this separate rendering, so I thought it should be reflected.

**Comment by kensongoo** [comment]
@tomchentw any chance of merging this feature to the master soon? I was thinking of adding the same feature.

**Comment by tomchentw** [comment]
Released [v7.1.0](https://github.com/tomchentw/react-google-maps/releases/tag/v7.1.0)

**Pull request merged**
