### PR TITLE
Linting Updates

### PR DESCRIPTION
**Pull request by oshalygin**
The first commit involves updating the linting configuration to leverage `prettier` along with removing `back-ticks` as a strict rule.  This gives the codebase a bit more flexibility, although it should be noted that prettier has a preference for double quotes and if we go with single quotes that will reflect across the board.

The second commit leverages the eslint plugin for prettier to run the linter against the codebase with `prettier` and subsequently updating the files that need to conform to it.  The way that this was done was `eslint --fix`

Note: Codebase updated to use prettier with `single-quotes`.  Batticks are still allowed(as they have a use), but single quote should be used when template literals are not required.

### CODE REVIEW

**Comment by oshalygin** [comment]
Perfect will do!  

Side note/question:  I ran `build:lib` to regen the lib folder with the changes babelified, should we not be doing that?  Moreso, should we even have a `/lib` folder?

**Comment by oshalygin** [comment]
Updated the PR:  

* Set single quotes as the standard enforced by prettier
* Removed changes to `/lib`

**Comment by oshalygin** [comment]
I'll rebase with latest

**Comment by tomchentw** [comment]
No longer relevant. Close now.

**Pull request closed without merging**
