### PR TITLE
Added Placeholder to input element - Searchbox

### PR DESCRIPTION
**Pull request by Heedster**
Added a placeholder prop to SearchBox which will be passed to the input element.

### CODE REVIEW

**Comment by tomchentw** [comment]
Not sure if it's a good idea here since we open a door at `componentDidMount`, we might need to handle that in `componentWillReceiveProps` as well...

**Comment by Heedster** [comment]
But I would like to change the placeholder from "Enter a query" to something else. How can I achieve that?

**Comment by Heedster** [comment]
Any thing that I can do to achieve this?

**Comment by tomchentw** [comment]
Released [v4.6.2](https://github.com/tomchentw/react-google-maps/releases/tag/v4.6.2)

**Pull request closed without merging**
