### PR TITLE
Refactor controlled component

### PR DESCRIPTION
**Pull request by tomchentw**
## Why

Rewrite to [controlled] components according to discussions in #68.

[controlled]: https://facebook.github.io/react/docs/forms.html

## Breaking Changes
This commit rewrite this module from scratch.

* GoogleMaps -> GoogleMap
	- (Others Component names are the same)
* OverlayView
      - Now only accepts single child
* Remove asynchronous loading support
* The props are not directly served as options for all google.maps instance.
	- Instead, we convert setters to props and also expose getters on component instance.
* To set an option directly, you can now pass options object
	just the same way as using Google Maps JavaScript APIs.
* Expose props have two representation: controlled & uncontrolled
	- uncontrolled props will have a `default${ PropName }` name
	- controlled props will be `${ propName }` as you expected
* Uncontrolled props will be used only when the instance first mounted
* Controlled props will call its corresponding setters **every** time rendered

MIGRATION GUIDE:

It introduces **controlled property** concept into the module. Most of the case, your application would like to have **uncontrolled** property. So change your component like this:

Before (v1.x.x):

```js
<Marker
      key={this.props.key}
      position={this.props.position}
      animation={this.props.animation}
      onRightclick={this.handleMarkerRightclick} />
```

After (v2.x.x):

```js
<Marker
      key={this.props.key}
      defaultPosition={this.props.position}
      defaultAnimation={this.props.animation}
      onRightclick={this.handleMarkerRightclick} />
```

The properties with *default-* prefix is **uncontrolled** property. It will only be set **ONCE** when the component is first-time mounted. Any further changes to your React props/state will **NOT** affect this marker (So it's **uncontrolled** from the view of React). Who can change the marker, you may ask. The answer is, only the component from google.maps.

But sometimes, we may want the marker's position changed according to current state. In that case, you have to provide **controlled** property to the `<Marker [position={this.state.position}>`. By doing so, the marker's position will change *every* time the React props/state changes. However, it will not intercept the changes made by the component from google.maps. This is because for the `<Marker>` itself, it doesn't know what events from google.maps will change its component. So the consumer who uses "react-google-maps" will have to manually handle this in their codebase.

### CODE REVIEW

**Comment by tomchentw** [comment]
Released [v2.0.0] and [v2.0.1].

[v2.0.0]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.0
[v2.0.1]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.1

**Comment by ksavenkov** [comment]
Migrating to 2.0.1. I have replaced `mapPane` option for `OverlayView` with `defaultMapPaneName` (as it is definitely uncontrolled', and now it halts on mapPaneName is not defined. If I use `mapPaneName`, then there's a react warning that required `defaultMapPaneName` property is not set. As I understand, I shouldn't specify them both, right?

**Comment by tomchentw** [comment]
@ksavenkov yes, I believe we could safely remove `isRequired` attribute in the `OverlayViewCreator`: http://git.io/v3vQZ . Is that correct?

**Comment by tomchentw** [comment]
Released [v2.0.2].

[v2.0.2]: https://github.com/tomchentw/react-google-maps/releases/tag/v2.0.2

**Pull request merged**
